Small demontration of homegeneous vectors

In [1]:
import numpy as np

Euclidean vector

In [2]:
x = np.array([1, 2, 3])

x

array([1, 2, 3])

The same vector, but in homogeneous coordinates

In [3]:
x_h = np.array([1, 2, 3, 1])

x_h

array([1, 2, 3, 1])

The same vector, but with the homogeneous representation scaled by 5

In [4]:
y = np.array([5 * 1, 5 * 2, 5 * 3, 5])
y

array([ 5, 10, 15,  5])

Recovering the Euclidean vector:

1. Divide by the last elements
2. Take all elements but the last

In [5]:
(y / y[-1])[:-1]

array([1., 2., 3.])